'use client';
import {useEffect,useState} from 'react';
import AppShell from '../../components/AppShell';
import {addPlan,fetchPlans,fetchSources} from '../../lib/dataService';

export default function WorkPlan(){
 const [plans,setPlans]=useState([]),[sources,setSources]=useState([]),[form,setForm]=useState({week_of:new Date().toISOString().slice(0,10),source_ids:[],learning_goal:'',activities:'',expected_hours:'10',dash_deliverable:'',status:'planned'});
 useEffect(()=>{Promise.all([fetchPlans(),fetchSources()]).then(([p,s])=>{setPlans(p);setSources(s)})},[]);
 async function submit(e){e.preventDefault(); const row=await addPlan({...form,expected_hours:Number(form.expected_hours)}); setPlans([row,...plans]); setForm({...form,source_ids:[],learning_goal:'',activities:'',expected_hours:'10',dash_deliverable:''});}
 function toggle(id){setForm({...form,source_ids:form.source_ids.includes(id)?form.source_ids.filter(x=>x!==id):[...form.source_ids,id]})}
 return <AppShell><div className="pageHead"><div><div className="eyebrow">PERSONALIZED CURRICULUM</div><h1>Weekly Work Plan</h1><p>Mentor and student agree on a focused set of learning activities for the coming week, then review and adjust based on progress.</p></div></div>
 <div className="grid2"><section className="panel"><h2>Create Weekly Mission</h2><form className="formGrid" onSubmit={submit}><label>Week of<input type="date" value={form.week_of} onChange={e=>setForm({...form,week_of:e.target.value})}/></label><label>Learning Goal<textarea required value={form.learning_goal} onChange={e=>setForm({...form,learning_goal:e.target.value})} placeholder="What should the student understand or be able to do by the next mentor meeting?"/></label><label>Activities<textarea required value={form.activities} onChange={e=>setForm({...form,activities:e.target.value})} placeholder="Readings, AEGIS injects, assignment work, analysis, briefing, research…"/></label><label>Expected Hours<input type="number" min="0" step="0.5" value={form.expected_hours} onChange={e=>setForm({...form,expected_hours:e.target.value})}/></label><label>Dash Deliverable<textarea value={form.dash_deliverable} onChange={e=>setForm({...form,dash_deliverable:e.target.value})}/></label><button className="primaryBtn">SAVE WEEKLY MISSION</button></form></section>
 <section className="panel"><h2>Select Astrum Sources</h2><p>Choose only what is relevant to the student this week.</p><div className="tagRow">{sources.slice(0,20).map(s=><button type="button" key={s.id} onClick={()=>toggle(s.id)} className={form.source_ids.includes(s.id)?'primaryBtn':'secondaryBtn'}>{s.id}</button>)}</div><p>{form.source_ids.length?`Selected: ${form.source_ids.join(', ')}`:'No sources selected yet.'}</p></section></div>
 <h2 className="sectionTitle">Previous Weekly Missions</h2>{plans.length?<table className="table"><thead><tr><th>Week</th><th>Goal</th><th>Sources</th><th>Expected h</th><th>Status</th></tr></thead><tbody>{plans.map(p=><tr key={p.id}><td>{p.week_of}</td><td>{p.learning_goal}</td><td>{(p.source_ids||[]).join(', ')}</td><td>{p.expected_hours}</td><td>{p.status}</td></tr>)}</tbody></table>:<div className="empty">No weekly missions yet.</div>}</AppShell>
}
